### ISSUE TITLE
Numba for people who don't want to install it

### ISSUE THREAD

**Issue by ewoudwempe** [lenstronomy/lenstronomy#241]
Edit: ah, nevermind, I think you reverted that commit in the end, I should read the commits a bit better, apologies! Still, a better solution is probably a good idea?
#240 reverted some, in my opinion, quite helpful numba decorators, especially the neighborselect decorator sped up the lens equation solver quite a bit for me (see #227). Can I just add them back, or do we need some mechanism to help people who do not have numba installed? 

I suppose we could just make the jit decorator do nothing if the numba package fails to load, so that all code works if numba is not installed, would that solve your issue @dangilman?

**Comment by dangilman** [comment]
ah, the @jit decorators cause my code to crash when I run on a cluster so I remove them on my branch. I guess I forgot to put them back in when submitting the pull request

**Comment by ewoudwempe** [comment]
Actually, you didn't, I was just a bit confused by the commits :)

**Comment by sibirrer** [comment]
some people are indeed struggling with numba (either the install or the configuration on clusters). Having a better configuration method (currently you would need to over-write on initialization the variables in numba_util.py) and/or a drop-back to pure python in case it fails would be great indeed.

**Comment by sibirrer** [comment]
I close this issue since there is a configuration file that enables to disable numba completelyhttps://github.com/lenstronomy/lenstronomy/blob/main/lenstronomy/Conf/conf_default.yaml
