### ISSUE TITLE
Typo in curved_arc_tan_diff

### ISSUE THREAD

**Issue by acagansengul** [lenstronomy/lenstronomy#344]
Hello. I think there is a typo in line 29 of https://github.com/sibirrer/lenstronomy/blob/main/lenstronomy/LensModel/Profiles/curved_arc_tan_diff.py.

It says 'dtan_dtab' when I think it should say 'dtan_dtan'

**Comment by sibirrer** [comment]
Thank you @acagansengul !
This will be fixed with the next merge of my own branch into lenstronomy/lenstronomy
