### ISSUE TITLE
maintaining and updating publication list

### ISSUE THREAD

**Issue by sibirrer** [lenstronomy/lenstronomy#356]
currently, the PUBLICATIONS.rst file is aimed at maintaining a list of publications making use of lenstronomy. This is time-consuming to maintain and might also not be up to date, or publications might be missing.

Auto-query (which will also include citations to lenstronomy that do not make actual use of the code) might be an alternative. Other alternative suggestions are highly welcomed!

**Comment by ajshajib** [comment]
I agree, that keeping the PUBLICATIONS.rst file updated is time-consuming and I think it's a little beyond actual scope of software development. Probably in that document we can simply provide this link to an ADS custom query search result, where all the papers referencing lenstronomy would be listed: https://ui.adsabs.harvard.edu/search/p_=0&q=citations(author%3A%22%5EBirrer%22%20title%3A%22lenstronomy%22)&sort=date%20desc%2C%20bibcode%20desc

**Comment by sibirrer** [comment]
thanks @ajshajib ! 
In the latest PR I just added the link and a small description. Further improvements can be made but are not strictly necessary
