### ISSUE TITLE
`ModelPlot()` executes linear solver when `linear_solver=False`

### ISSUE THREAD

**Issue by ajshajib** [lenstronomy/lenstronomy#380]
https://github.com/lenstronomy/lenstronomy/blob/c6e912500aac5d50c4812dd268dc196abb0223f3/lenstronomy/Plots/model_plot.py#L53

Is this behavior intended when `linear_solver=False`? I was trying to plot corresponding to provided `amp` values in light profiles without the linear solver to change them.

**Comment by sibirrer** [comment]
HI @ajshajib, currently, I think, the plotting is mostly used by inserting directly results from PSO or MCMC chains, and those are in default mode without the amp parameters. Also, if you have multiple imaging bands, it might not be clear what bands the amp parameters refer to. I am happy to have it changed as long as there does not to be any tweaks to the outputs of the previous most likely use case.

**Comment by sibirrer** [comment]
Ah, sorry, this is actually a bug. The linear_solve=False gets only applied when calculating the likelihood but not by directly computing the image with image_linear_solve(), so this needs to be fixed indeed

**Comment by ajshajib** [comment]
@sibirrer Thanks for the clarification. I was proividing the `amp` values inserted into there corresponding dictionaries within `kwargs_params`. So for multiple bands it should not be ambiguous as `kwargs_model` and `kwargs_params` in combination would set the appropriate parameter handling.  Since it is possible to have `amp` treated as non-linear parameters in the likelihood during PSO/MCMC, it will be useful to not alter the `amp` values coming out of PSO or MCMC if `linear_solve = False` is set. I am just wondering about consistency between fitting and plotting with `linear_solver = False` chosen.

**Comment by sibirrer** [comment]
@ajshajib do you want to assign either me or you to this issue such that we are not duplicating effort to solve it? (if you can solve it, I'd appreciate it). Thank you!

**Comment by ajshajib** [comment]
@sibirrer, actually, would it be possible for you to fix it rather easily? I initially thought it would be easy to fix it by putting these two lines within an `if` statement:

```
model, error_map, cov_param, param = self._imageModel.image_linear_solve(inv_bool=True, **kwargs_params)
            check_solver_error(param)
```

But, `cov_param` etc. is needed later, and it looks to me that it would be a little more complicated to fix things by needing to do stuff probably in the `MultiLinear` and/or `SingleBandMultiModel` class(es). Can you kindly take a jab at it in the short term if possible? If I were do it, I would have to postpone it until next week or later. I needed this fix for fitting `R_eff` for a TDCOSMO lens, but I may find a quick hack for working around this bug for the time being.

**Comment by sibirrer** [comment]
@ajshajib , I took a look and it indeed requires a bit a larger fix. I can come up with a quicker fix for a single band, but it is not even clear how the input format would look like for multiple bands since the amp values will be different, and as such the routine would be ill-posed. Hard to predict how long it takes but definitely something that needs to be fixed for single band

**Comment by ajshajib** [comment]
How about only allowing `linear_solver=True` to work for single band cases, but put an error message when this feature is accessed in the multi-band case?

**Comment by sibirrer** [comment]
yes, that works. What I still need is a param object of the list of all linear parameters to be generated. the cover_param can still be computed by the linear inversion. I give it a try and make a PR

**Comment by sibirrer** [comment]
@ajshajib is this still an issue? Otherwise we can close it and re-open if needed

**Comment by ajshajib** [comment]
No, I think this is fixed. I didn't realize that this issue was not automatically when #381 was merged. I am closing it.
