### ISSUE TITLE
chain_plot.psf_iteration_compare crashes when oversampled psf with psf error map at data resolution is used

### ISSUE THREAD

**Issue by LyneVdV** [lenstronomy/lenstronomy#384]
at line 163 in Plots.chain_plot  `im = ax.matshow(np.log10(psf_error_map*psf.kernel_point_source**2), origin='lower', **kwargs)` if the psf.kernel_point_source is oversampled and thus do not match the psf_error_map resolution/number of pixels, the multiplication can not occur and the plot crashes.

**Comment by sibirrer** [comment]
Hi @LyneVdV , pdf.kernel_point_source should always be the down-sampled kernel. It seems that the error map and the downsampled kernel do not have exactly the same size. Did you encounter an error when running the fitting or only in the plotting?

**Comment by LyneVdV** [comment]
It appears that pdf.kernel_point_source is indeed down-sampled. However, when installing lenstronomy using `pip install lenstronomy` (and not git clone url), the version is said to be 1.11.0 but the chain_plot.py file is not the same as the one here on git hub. And in this "1.11.0 pip version", the corresponding line is `im = ax.matshow(np.log10(psf_error_map*psf_out**2), origin='lower', **kwargs) ` and psf_out is not downsampled. So it seems there is no issue on the version available from git hub, it was in fact a issue of installation procedure: I really don't know why the version installed with pip, which is said to be 1.11.0, is not identical to the one on git hub.

**Comment by LyneVdV** [comment]
As a side note, the plotting with the git hub version 1.11.0 may also be improved in terms of placing the text "psf error map": it is placed at `delta_x, n_kernel-delta_y` but those values are based on `len(psf_in)`, i.e. based on the oversampled length, hence placing the text at a weird position (in my case way above the subplot, creating a large white space between the plots of the different bands).

**Comment by sibirrer** [comment]
Ah, yeah, it might be that with the latest pip version, this was not fixed yet. Pip releases are not as up to date as the main branch, but I guess we should do another one shortly. Also thanks for the note on the pixel grid, indeed, that needs to be changed. I just merged a minor PR that hopefully solves it (if you upgrade the main branch installation). Thanks a lot!

**Comment by LyneVdV** [comment]
Yes it solves the issue of weird placing of the "psf error map" text ! Thank you :) !
