### ISSUE TITLE
PSF Fitting

### ISSUE THREAD

**Issue by amn3142** [lenstronomy/lenstronomy#427]
Running lenstronomy 1.11.0
In PSF fitting, in the step psf_estimate_individual,  
In line 332:
 correction = residuals_shifted - np.mean(residuals_shifted)

The correction does not appear to be centered (nor does the residual). However the kernel_guess, appears to be the original point source function guess, which is centered.

I've made some intermediate plots of the different steps of psf_estimate_individual, attached.

My specific use case is modelling four unlensed point sources. 
The point sources are initialized at:
[{'ra_image': [18.4117369], 'dec_image': [16.79978017], 'point_amp': [1]}, {'ra_image': [23.58548622], 'dec_image': [15.9161221], 'point_amp': [1]}, {'ra_image': [29.01286391], 'dec_image': [20.13762326], 'point_amp': [1]}, {'ra_image': [19.82409235], 'dec_image': [31.87333369], 'point_amp': [1]}]

For my data 1 "arcsecond"= 1 pixel.
result from line 319 in psf_fitting.py, parameter name is 'shifted_residuals'
![shifted_residuals_2](https://user-images.githubusercontent.com/16903098/225205062-943416fd-b9d8-4f0d-84e1-f3743c3a1fca.png)
Result from line 332, parameter name is 'correction':

![correction_2](https://user-images.githubusercontent.com/16903098/225205059-46322e81-7774-42bc-abac-f345c72907b1.png)

kernel_guess, in line 334
![kernel_guess](https://user-images.githubusercontent.com/16903098/225205065-23b170f1-c49a-4dc8-9d22-112430fa048c.png)

My concern is that in line 334, kernal_new = kernel_guess+correction, but 'kernel_guess' appears to be centered at a completely different location from 'correction'.  From what I can tell, kernel_guess, is the original PSF kernel and so we would not expect it to be centered at the same location as the image. This seems problematic based on the algorithm.

I would have expected we wanted kernel_guess to be rendered at the image location.

**Comment by sibirrer** [comment]
Hi @amn3142 , thank you for posting the issue!
I am not quite following what plots you are making of what quantities in the code. Can you please state where you made this plots of what quantities? The shifting of the residuals only are the sub-pixel level shifts. They 'should' all be relative to the center of the point sources.

**Comment by amn3142** [comment]
Sorry Simon, I tried adding some clarifying comments about where each element is coming from as well as what I think the issue is.

**Comment by sibirrer** [comment]
Thanks @amn3142 , can you send me perhaps a notebook? It looks like the positions of the point sources do not match or the residuals are actually coming from other point sources and not the one that is reconstructed.

**Comment by amn3142** [comment]
Ahhh that makes total sense. There is one image that is much brighter than the others. I was stupidly assuming it was the residual of the one we were interested in. Sorry.... Thanks so much for looking. I will increase mask nearest neighbor and look again.

**Comment by amn3142** [comment]
That was definitely it. I'm so sorry. I'll close it.
