### ISSUE TITLE
Change keyword provided to `"update_settings"` fitting-sequence step

### ISSUE THREAD

**Issue by ajshajib** [lenstronomy/lenstronomy#448]
https://github.com/lenstronomy/lenstronomy/blob/e00f37668c2eab8ccff84dd8968ac2d76b53767d/lenstronomy/Workflow/fitting_sequence.py#L501

I think, it would be more consistent to change the variable name `cosmo_add_fixed` to `special_add_fixed`, and similarly `cosmo_remove_fixed` to `special_remove_fixed`.  It will be more self-explanatory to go with the naming `special` in `kwargs_params`, and they are the expected variable names in `UpdateManager.update_fixed()` in the first place.

Is there any downside, except that it would not be backward compatible?

**Comment by sibirrer** [comment]
good point! This is indeed an artifact from old times when in this category were only cosmology parameters. The incompatibility issue I see as only minor.

**Comment by ajshajib** [comment]
Ok! I will send a PR soon then.

**Comment by ajshajib** [comment]
Closed with #449.
