### ISSUE TITLE
Changing sampling algorithm naming conventions in FittingSequence

### ISSUE THREAD

**Issue by nataliehogg** [lenstronomy/lenstronomy#477]
In the current version of FittingSequence, some sampling algorithms are accessed via a "top level" function named after the general algorithm i.e. mcmc() which contains the ensemble samplers emcee and zeus, and nested_sampling(), which contains the nested samplers dynesty, multinest and polychord. Apart from that, the Nautilus and Cobaya samplers are accessed separately by directly calling their classes from Sampling.Samplers. 

This process is a bit convoluted and could be streamlined in various ways:
1. Have all samplers accessed via a top-level function named after the specific algorithm i.e. metropolis_hastings(), ensemble_MCMC(), nested_sampling(), importance_nested_sampling(). The user would first pass a kwarg calling the sampling method, and in the cases where there is more than one option (ensemble_MCMC and nested_sampling), a kwarg for the specific software.
2. Have all samplers directly accessed via the software names i.e. by passing kwargs such as 'emcee', 'zeus', 'dynesty' etc directly to the fitting sequence.

Issue: either of these options will introduce backwards incompatibility as it will likely require changing the 'MCMC' kwarg most commonly passed to the fitting sequence.

**Comment by ajshajib** [comment]
Based on what @dangilman suggested for backward compatibility in #475, I think the following way forward will satisfy all sides:

1. Have the fitting sequence keywords be based on software names, e.g., `'emcee'`, `'PyPolyChord'`, `'Cobaya'` etc.
2. Keep the existing keyword `'MCMC'` for backward compatibility that would simply redirect to `'emcee'`.

What do you think?

**Comment by nataliehogg** [comment]
@ajshajib @sibirrer thanks for the suggestions! I will implement it as you say and open a pull request soon.
