### ISSUE TITLE
Code comment errors in NFW profile

### ISSUE THREAD

**Issue by zijun-gao** [lenstronomy/lenstronomy#480]
Dear sibirrer:
It seems like a code comment errors in your ~/LensModel/Profiles/NFW.py file:
...
153 def density_2d(self, x, y, Rs, rho0, center_x=0, center_y=0):
           """
              projected two dimensional NFW profile (kappa*Sigma_crit)
...
You comment function density_2d() will return kappa*Sigma_crit, but after I calculated and checked your code, I found that it will  return kappa instead of kappa*Sigma_crit. This is a small issue, I don't think it will affect other parts of the code, but it may mislead users who need to use or rewrite the NFW distribution.

Best wishes,
zj_gao

**Comment by sibirrer** [comment]
Hi @zijun-gao , thank you very much for the issue! Indeed, the function (only internally in the NFW class being called, is computing kappa (it really depends a bit on how rho0 is defined in the input). I updated the documentation in this PR #481
