### ISSUE TITLE
diff_method 0 not supported. Chose among "square" or "cross"

### ISSUE THREAD

**Issue by Tabibrh** [lenstronomy/lenstronomy#491]
after giving all the parameters as given `below:
`f_xx, f_xy, f_yx, f_yy=lens_model.hessian(x1, x2, theta_E, gamma, e1, e2)`
x1, x2 ,theta_E, gamma, e1,e2 all were provided but after running the program for SPEMD, i get the following error:
Traceback (most recent call last):
  File "/home/tabib/Documents/Project 1/test.py", line 21, in <module>
    f_xx, f_xy, f_yx, f_yy=lens_model.hessian(x1, x2, theta_E, gamma, e1, e2)
  File "/home/tabib/anaconda3/envs/phy1/lib/python3.7/site-packages/lenstronomy/LensModel/lens_model.py", line 227, in hessian
    raise ValueError('diff_method %s not supported. Chose among "square" or "cross".' % diff_method)
ValueError: diff_method 0 not supported. Chose among "square" or "cross".

**Comment by sibirrer** [comment]
Hi @Tabibrh , thanks for the issue. The LensModel class function calls are flexible to allow for superpositions of lens models. You need to provide the deflector model parameters as lists of dictionaries. Have a look at the description of the function you are using or the starting guide notebook

**Comment by Tabibrh** [comment]
hessian(x, y, kwargs, k=None, diff=None, diff_method='square') where k is written as k – only evaluate the k-th lens model i need to do it for the SPEMD so what value of k should  I give ,  i dont see any specified number for a particular lens model.... so when i run it like `f_xx, f_xy, f_yx, f_yy=lens_model.hessian(x1, x2, theta_E, gamma, e1, e2, k=None, diff=None, diff_method='square')`   I get the following error TypeError: hessian() got multiple values for argument 'k'

**Comment by sibirrer** [comment]
the input is (x, y, kwargs). You have a different input and need to describe kwargs = [{'theta_E': .......}]. Please look at the examples in the jupyter notebook

**Comment by Tabibrh** [comment]
Is this the notebook , if not can you share it 
https://github.com/lenstronomy/lenstronomy-tutorials/blob/main/Notebooks/GettingStarted/starting_guide.ipynb

**Comment by sibirrer** [comment]
> Is this the notebook , if not can you share it
> https://github.com/lenstronomy/lenstronomy-tutorials/blob/main/Notebooks/GettingStarted/starting_guide.ipynb

yes

**Comment by Tabibrh** [comment]
i sorry to bother you so much but  I dont know why every time i am getting ijnto one error or another. 
`from lenstronomy.LensModel.lens_model import LensModel
import numpy as np
import matplotlib.pyplot as plt

# Create the LensModel instance with the SPEMD profile
lens_model = LensModel(['SPEMD'])

# Define the grid of source positions where you want to compute the magnification
x1 = np.arange(-3, 3, 0.001)
x2 = np.arange(-3, 3, 0.001)

# Parameters for the SPEMD profile
kwargs = {'theta_E': 1.94, 'gamma': 2.36, 'e1': 0.2, 'e2': 0, 's_scale': 0.11, 'center_x': 0, 'center_y': 0}

# Calculate the magnification at the specified source positions
hessian = lens_model.hessian(x1, x2, kwargs)`

but i encounter this error:
`/home/tabibrh/anaconda3/envs/lensing/bin/python "/home/tabibrh/Documents/Project 1/xp.py"
/home/tabibrh/anaconda3/envs/lensing/lib/python3.11/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
Traceback (most recent call last):
  File "/home/tabibrh/Documents/Project 1/xp.py", line 16, in <module>
    magnification = lens_model.magnification(x1, x2, kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tabibrh/anaconda3/envs/lensing/lib/python3.11/site-packages/lenstronomy/LensModel/lens_model.py", line 312, in magnification
    f_xx, f_xy, f_yx, f_yy = self.hessian(x, y, kwargs, k=k, diff=diff, diff_method=diff_method)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tabibrh/anaconda3/envs/lensing/lib/python3.11/site-packages/lenstronomy/LensModel/lens_model.py", line 221, in hessian
    return self.lens_model.hessian(x, y, kwargs, k=k)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tabibrh/anaconda3/envs/lensing/lib/python3.11/site-packages/lenstronomy/LensModel/single_plane.py", line 119, in hessian
    f_xx_i, f_xy_i, f_yx_i, f_yy_i = func.hessian(x, y, **kwargs[i])`

**Comment by sibirrer** [comment]
I don't see an error here. I see a deprecation warning but the should not lead to a raise from the text you copied here

**Comment by Tabibrh** [comment]
what do you suggest I should do ?

**Comment by sibirrer** [comment]
you need to put brackets as kwargs = [{'theta_E':...}] as I pointed you to and as it was in the example notebook. I recommend you following the examples very closely, either copy-pasting them directly and then modifying.

**Comment by Tabibrh** [comment]
Yeesssss it worked , I am greatful to you for helping me replying my annoying questions but now that i am trying to take this full time I will keep asking you questions , once again I am very greatful.
