### ISSUE TITLE
Handling of source indexes in Multi-band modelling

### ISSUE THREAD

**Issue by PierreBoccard** [lenstronomy/lenstronomy#578]
There seems to be an issue with how Lenstronomy deals with the kwargs_souce parameters and indexes in the case of multi-band modeling. Right now, the code I used to run doesn't work and the problem seems to be coming from the `update_linear_kwargs()` function in the `class SingleBandMultiModel` [https://github.com/lenstronomy/lenstronomy/blob/main/lenstronomy/ImSim/MultiBand/single_band_multi_model.py](url) line 348.
In particular, how the code handles the different source indexes from the different bands.

I was using before that the multi-plane dev branch, which I still have a version of on my computer, but the comparison to understand the issue is hard as the handling of the kwargs_update is quite different. 

This is the error output I'm having : 

<img width="999" alt="Screenshot 2024-01-29 at 11 18 05" src="https://github.com/lenstronomy/lenstronomy/assets/97764885/dec5d427-c4da-4193-aaa7-db4ae33823b9">

In more detail, I have three bands with a total of 15 indexes (5 per band but not arranged in ascending order). This is the printout from the `select_kwargs()` function : 

<img width="216" alt="Screenshot 2024-01-29 at 11 27 51" src="https://github.com/lenstronomy/lenstronomy/assets/97764885/b7dc2dbd-6332-41f5-8be2-9d25fcbf5e7c">

I'm not sure how to fix the issue, if anyone has an insight or feedback, it would be much appreciated, thank you.

**Comment by aymgal** [comment]
Indeed @PierreBoccard your issue is very similar to one I had recently, which was fixed with e.g. PR #575 .

**Comment by ajshajib** [comment]
@PierreBoccard, is this issue fixed now after #575? If so, please close the issue.
