### ISSUE TITLE
Definition of multipoles breaks down for non-zero ellipticities 

### ISSUE THREAD

**Issue by Hadrien-Pgnt** [lenstronomy/lenstronomy#642]
Regarding `lenstronomy.LensModel.Profiles.multipole` and ` lenstronomy.LensModel.Profiles.epl_multipole_m3m4 `

The current definition for the multipoles is only consistent with the current physical interpretation (e.g. boxy/disky isocontours for the m=4 multipole) if the axis ratio is q=1. In studies of the isophotes of galaxies (e.g. Bender et al 1988), the definition is indeed $\delta R_m = a_m \cos(m(\varphi-\varphi_m))$ for the multipole perturbation around the ellipse, but the quantities used are the elliptical radius and the eccentric anomaly: $R = \sqrt{qx^2+y^2/q}, \varphi = \arctan(qx,y)$
not the usual polar coordinates $r=\sqrt{x^2+y^2}, \phi = \arctan(x,y)$

The difference is noticeable for large ellipticities ie. q very different from 1. This gives, for instance, a peanut-shaped pattern when $a_4 <0$ instead of a boxy one (see figure below)… For reasonables values of q (~0.8), this shouldn't have too much impact but it still makes interpretation of $a_m$ difficult since the pattern of deviation depends on the axis ratio.
![image](https://github.com/user-attachments/assets/63b86671-8b34-4d5d-a590-4aadfc42e33c)

The main difficulty after making the change in variables is that the potential and deflection angles are much harder to compute (substituting the new variables in the old formulas won't work since the Laplacian has a different expression...).
Currently working on a fix !

**Comment by dangilman** [comment]
Pull request 643 dealt with this issue by introducing a new elliptical multipole lens mass profile for the m=3 and m=4 terms.
