### ISSUE TITLE
Time-delay likelihood is incorrect if several point sources are used. 

### ISSUE THREAD

**Issue by martin-millon** [lenstronomy/lenstronomy#678]
This statement is always False when self._measurement_bool_list is a list of lists, which is the case when you have several 'LENSED_POSITION' point sources: https://github.com/lenstronomy/lenstronomy/blob/f731c7c9fe2fd91ba6921184baaf151074a02ea5/lenstronomy/Sampling/Likelihoods/time_delay_likelihood.py#L68

I am working on a PR to solve this.

**Comment by sibirrer** [comment]
@martin-millon the original use of this is intent to only have one True/False statement per point_source_model, either a source is time-variable and measurements exist, or the source is static. We either need to specify the use or indeed fix it to not cause confusions. Thank you for pointing this out and looking forward to the PR!

**Comment by martin-millon** [comment]
The proposed solution should conserve the previous behavior if default arguments are provided. You can now provide a list of list of boolean in `time_delay_measurement_bool_list`. For example, for 2-point sources, imaged 4 times each (3 time-delays), you can provide `time_delay_measurement_bool_list=[[True, True, True], [True, False, False]]`.

**Comment by martin-millon** [comment]
Fixed in #680
